<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>LinqBridge.Tests</RootNamespace>
    <AssemblyName>LinqBridge.Tests</AssemblyName>
    <TargetFramework>net30</TargetFramework>
    <TargetFrameworkSubset />
    <NoWarn>1685</NoWarn>
    <DebugType>full</DebugType>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Net4x.BaseTypes" Version="1.3.1.*" Aliases="bt" />
    <PackageReference Include="NUnit" Version="2.6.4" />
    <PackageReference Include="Net20.Runtime" Version="$(Net20TypeInfoVersion).$(VersionBuildSuffix)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Net30.LinqBridge\Net20.LinqBridge.csproj" />
  </ItemGroup>
</Project>