//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Properties.Core", typeof(Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array is not long enough to copy all the items in the collection. Check array index and length..
        /// </summary>
        internal static string Arg_ArrayPlusOffTooSmall {
            get {
                return ResourceManager.GetString("Arg_ArrayPlusOffTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashSet capacity is too big..
        /// </summary>
        internal static string Arg_HSCapacityOverflow {
            get {
                return ResourceManager.GetString("Arg_HSCapacityOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements of the AdjustmentRule array must not contain ambiguous time periods that extend beyond the DateStart or DateEnd properties of the element..
        /// </summary>
        internal static string Argument_AdjustmentRulesAmbiguousOverlap {
            get {
                return ResourceManager.GetString("Argument_AdjustmentRulesAmbiguousOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements of the AdjustmentRule array must not contain invalid time periods that extend beyond the DateStart or DateEnd properties of the element. .
        /// </summary>
        internal static string Argument_AdjustmentRulesInvalidOverlap {
            get {
                return ResourceManager.GetString("Argument_AdjustmentRulesInvalidOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AdjustmentRule array cannot contain null elements..
        /// </summary>
        internal static string Argument_AdjustmentRulesNoNulls {
            get {
                return ResourceManager.GetString("Argument_AdjustmentRulesNoNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements of the AdjustmentRule array must be in chronological order and must not overlap..
        /// </summary>
        internal static string Argument_AdjustmentRulesOutOfOrder {
            get {
                return ResourceManager.GetString("Argument_AdjustmentRulesOutOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements of the AdjustmentRule array must not contain Daylight Saving Time periods that overlap adjacent elements in such a way as to cause invalid or ambiguous time periods..
        /// </summary>
        internal static string Argument_AdjustmentRulesrDaylightSavingTimeOverlap {
            get {
                return ResourceManager.GetString("Argument_AdjustmentRulesrDaylightSavingTimeOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements of the AdjustmentRule array must not contain Daylight Saving Time periods that overlap the DateStart or DateEnd properties in such a way as to cause invalid or ambiguous time periods..
        /// </summary>
        internal static string Argument_AdjustmentRulesrDaylightSavingTimeOverlapNonRuleRange {
            get {
                return ResourceManager.GetString("Argument_AdjustmentRulesrDaylightSavingTimeOverlapNonRuleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion could not be completed because the supplied DateTime did not have the Kind property set correctly.  For example, when the Kind property is DateTimeKind.Local, the source time zone must be TimeZoneInfo.Local..
        /// </summary>
        internal static string Argument_ConvertMismatch {
            get {
                return ResourceManager.GetString("Argument_ConvertMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied DateTime must have the Year, Month, and Day properties set to 1.  The time cannot be specified more precisely than whole milliseconds..
        /// </summary>
        internal static string Argument_DateTimeHasTicks {
            get {
                return ResourceManager.GetString("Argument_DateTimeHasTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied DateTime includes a TimeOfDay setting.   This is not supported..
        /// </summary>
        internal static string Argument_DateTimeHasTimeOfDay {
            get {
                return ResourceManager.GetString("Argument_DateTimeHasTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid..
        /// </summary>
        internal static string Argument_DateTimeIsInvalid {
            get {
                return ResourceManager.GetString("Argument_DateTimeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied DateTime is not in an ambiguous time range..
        /// </summary>
        internal static string Argument_DateTimeIsNotAmbiguous {
            get {
                return ResourceManager.GetString("Argument_DateTimeIsNotAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied DateTime must have the Kind property set to DateTimeKind.Unspecified..
        /// </summary>
        internal static string Argument_DateTimeKindMustBeUnspecified {
            get {
                return ResourceManager.GetString("Argument_DateTimeKindMustBeUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied DateTimeOffset is not in an ambiguous time range..
        /// </summary>
        internal static string Argument_DateTimeOffsetIsNotAmbiguous {
            get {
                return ResourceManager.GetString("Argument_DateTimeOffsetIsNotAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serverName cannot be an empty string.  Use &quot;.&quot; for current machine..
        /// </summary>
        internal static string Argument_EmptyServerName {
            get {
                return ResourceManager.GetString("Argument_EmptyServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified ID parameter &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Argument_InvalidId {
            get {
                return ResourceManager.GetString("Argument_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string Argument_InvalidOffLen {
            get {
                return ResourceManager.GetString("Argument_InvalidOffLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The REG_TZI_FORMAT structure is corrupt..
        /// </summary>
        internal static string Argument_InvalidREG_TZI_FORMAT {
            get {
                return ResourceManager.GetString("Argument_InvalidREG_TZI_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified serialized string &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Argument_InvalidSerializedString {
            get {
                return ResourceManager.GetString("Argument_InvalidSerializedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter cannot be an empty string..
        /// </summary>
        internal static string Argument_NeedNonemptyDelimiter {
            get {
                return ResourceManager.GetString("Argument_NeedNonemptyDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipeName cannot be an empty string..
        /// </summary>
        internal static string Argument_NeedNonemptyPipeName {
            get {
                return ResourceManager.GetString("Argument_NeedNonemptyPipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This flag may not be set on a pipe..
        /// </summary>
        internal static string Argument_NonContainerInvalidAnyFlag {
            get {
                return ResourceManager.GetString("Argument_NonContainerInvalidAnyFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateStart property must come before the DateEnd property..
        /// </summary>
        internal static string Argument_OutOfOrderDateTimes {
            get {
                return ResourceManager.GetString("Argument_OutOfOrderDateTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TimeSpan parameter cannot be specified more precisely than whole minutes..
        /// </summary>
        internal static string Argument_TimeSpanHasSeconds {
            get {
                return ResourceManager.GetString("Argument_TimeSpanHasSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DaylightTransitionStart property must not equal the DaylightTransitionEnd property..
        /// </summary>
        internal static string Argument_TransitionTimesAreIdentical {
            get {
                return ResourceManager.GetString("Argument_TransitionTimesAreIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAsyncResult object did not come from the corresponding async method on this type..
        /// </summary>
        internal static string Argument_WrongAsyncResult {
            get {
                return ResourceManager.GetString("Argument_WrongAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer cannot be null..
        /// </summary>
        internal static string ArgumentNull_Buffer {
            get {
                return ResourceManager.GetString("ArgumentNull_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serverName cannot be null. Use &quot;.&quot; for current machine..
        /// </summary>
        internal static string ArgumentNull_ServerName {
            get {
                return ResourceManager.GetString("ArgumentNull_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additionalAccessRights is limited to the PipeAccessRights.ChangePermissions, PipeAccessRights.TakeOwnership, and PipeAccessRights.AccessSystemSecurity flags when creating NamedPipeServerStreams..
        /// </summary>
        internal static string ArgumentOutOfRange_AdditionalAccessLimited {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_AdditionalAccessLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pipeName &quot;anonymous&quot; is reserved..
        /// </summary>
        internal static string ArgumentOutOfRange_AnonymousReserved {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_AnonymousReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Day parameter must be in the range 1 through 31..
        /// </summary>
        internal static string ArgumentOutOfRange_Day {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DayOfWeek enumeration must be in the range 0 through 6..
        /// </summary>
        internal static string ArgumentOutOfRange_DayOfWeek {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipeDirection.In or PipeDirection.Out required..
        /// </summary>
        internal static string ArgumentOutOfRange_DirectionModeInOrOut {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_DirectionModeInOrOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For named pipes, the pipe direction can be PipeDirection.In, PipeDirection.Out or PipeDirection.InOut. For anonymous pipes, the pipe direction can be PipeDirection.In or PipeDirection.Out..
        /// </summary>
        internal static string ArgumentOutOfRange_DirectionModeInOutOrInOut {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_DirectionModeInOutOrInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleInheritability.None or HandleInheritability.Inheritable required..
        /// </summary>
        internal static string ArgumentOutOfRange_HandleInheritabilityNoneOrInheritable {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_HandleInheritabilityNoneOrInheritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenImpersonationLevel.None, TokenImpersonationLevel.Anonymous, TokenImpersonationLevel.Identification, TokenImpersonationLevel.Impersonation or TokenImpersonationLevel.Delegation required..
        /// </summary>
        internal static string ArgumentOutOfRange_ImpersonationInvalid {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_ImpersonationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impersonationOptions contains an invalid flag..
        /// </summary>
        internal static string ArgumentOutOfRange_ImpersonationOptionsInvalid {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_ImpersonationOptionsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PipeAccessRights flag..
        /// </summary>
        internal static string ArgumentOutOfRange_InvalidPipeAccessRights {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_InvalidPipeAccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout must be non-negative or equal to -1 (Timeout.Infinite).
        /// </summary>
        internal static string ArgumentOutOfRange_InvalidTimeout {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_InvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of parameters must not exceed {0}. .
        /// </summary>
        internal static string ArgumentOutOfRange_MaxArgExceeded {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MaxArgExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxNumberOfServerInstances must either be a value between 1 and 254, or NamedPipeServerStream.MaxAllowedServerInstances (to obtain the maximum number allowed by system resources)..
        /// </summary>
        internal static string ArgumentOutOfRange_MaxNumServerInstances {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MaxNumServerInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of String parameters must not exceed {0}..
        /// </summary>
        internal static string ArgumentOutOfRange_MaxStringsExceeded {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MaxStringsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Month parameter must be in the range 1 through 12..
        /// </summary>
        internal static string ArgumentOutOfRange_Month {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size value should be greater than or equal to bufferSize..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedMaxFileSizeGEBufferSize {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedMaxFileSizeGEBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non negative number is required..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID parameter must be in the range {0} through {1}..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedValidId {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need valid log retention option..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedValidLogRetention {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedValidLogRetention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of files value should be greater than or equal to &apos;{0}&apos; for this retention.
        /// </summary>
        internal static string ArgumentOutOfRange_NeedValidMaxNumFiles {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedValidMaxNumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need valid PipeAccessRights value..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedValidPipeAccessRights {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedValidPipeAccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options contains an invalid flag..
        /// </summary>
        internal static string ArgumentOutOfRange_OptionsInvalid {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_OptionsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For named pipes, transmission mode can be TransmissionMode.Byte or PipeTransmissionMode.Message. For anonymous pipes, transmission mode can be TransmissionMode.Byte..
        /// </summary>
        internal static string ArgumentOutOfRange_TransmissionModeByteOrMsg {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_TransmissionModeByteOrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TimeSpan parameter must be within plus or minus 14.0 hours..
        /// </summary>
        internal static string ArgumentOutOfRange_UtcOffset {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_UtcOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the BaseUtcOffset and DaylightDelta properties must within plus or minus 14.0 hours..
        /// </summary>
        internal static string ArgumentOutOfRange_UtcOffsetAndDaylightDelta {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_UtcOffsetAndDaylightDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Week parameter must be in the range 1 through 5..
        /// </summary>
        internal static string ArgumentOutOfRange_Week {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keys from both parties must be the same size to generate a secret agreement..
        /// </summary>
        internal static string Cryptography_ArgECDHKeySizeMismatch {
            get {
                return ResourceManager.GetString("Cryptography_ArgECDHKeySizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys used with the ECDiffieHellmanCng algorithm must have an algorithm group of ECDiffieHellman..
        /// </summary>
        internal static string Cryptography_ArgECDHRequiresECDHKey {
            get {
                return ResourceManager.GetString("Cryptography_ArgECDHRequiresECDHKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys used with the ECDsaCng algorithm must have an algorithm group of ECDsa..
        /// </summary>
        internal static string Cryptography_ArgECDsaRequiresECDsaKey {
            get {
                return ResourceManager.GetString("Cryptography_ArgECDsaRequiresECDsaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeriveKeyMaterial requires an ECDiffieHellmanCngPublicKey..
        /// </summary>
        internal static string Cryptography_ArgExpectedECDiffieHellmanCngPublicKey {
            get {
                return ResourceManager.GetString("Cryptography_ArgExpectedECDiffieHellmanCngPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type CngAlgorithm..
        /// </summary>
        internal static string Cryptography_ArgMustBeCngAlgorithm {
            get {
                return ResourceManager.GetString("Cryptography_ArgMustBeCngAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type CngAlgorithmGroup..
        /// </summary>
        internal static string Cryptography_ArgMustBeCngAlgorithmGroup {
            get {
                return ResourceManager.GetString("Cryptography_ArgMustBeCngAlgorithmGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type CngKeyBlobFormat..
        /// </summary>
        internal static string Cryptography_ArgMustBeCngKeyBlobFormat {
            get {
                return ResourceManager.GetString("Cryptography_ArgMustBeCngKeyBlobFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type CngProvider..
        /// </summary>
        internal static string Cryptography_ArgMustBeCngProvider {
            get {
                return ResourceManager.GetString("Cryptography_ArgMustBeCngProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting a value requires that a key be set on the algorithm object..
        /// </summary>
        internal static string Cryptography_DecryptWithNoKey {
            get {
                return ResourceManager.GetString("Cryptography_DecryptWithNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML serialization of an elliptic curve key requires using an overload which specifies the XML format to be used..
        /// </summary>
        internal static string Cryptography_ECXmlSerializationFormatRequired {
            get {
                return ResourceManager.GetString("Cryptography_ECXmlSerializationFormatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm group &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Cryptography_InvalidAlgorithmGroup {
            get {
                return ResourceManager.GetString("Cryptography_InvalidAlgorithmGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Cryptography_InvalidAlgorithmName {
            get {
                return ResourceManager.GetString("Cryptography_InvalidAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified cipher mode is not valid for this algorithm..
        /// </summary>
        internal static string Cryptography_InvalidCipherMode {
            get {
                return ResourceManager.GetString("Cryptography_InvalidCipherMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified initialization vector (IV) does not match the block size for this algorithm..
        /// </summary>
        internal static string Cryptography_InvalidIVSize {
            get {
                return ResourceManager.GetString("Cryptography_InvalidIVSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key blob format &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Cryptography_InvalidKeyBlobFormat {
            get {
                return ResourceManager.GetString("Cryptography_InvalidKeyBlobFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified key is not a valid size for this algorithm..
        /// </summary>
        internal static string Cryptography_InvalidKeySize {
            get {
                return ResourceManager.GetString("Cryptography_InvalidKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding is invalid and cannot be removed..
        /// </summary>
        internal static string Cryptography_InvalidPadding {
            get {
                return ResourceManager.GetString("Cryptography_InvalidPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Cryptography_InvalidProviderName {
            get {
                return ResourceManager.GetString("Cryptography_InvalidProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the domain parameters from the XML string..
        /// </summary>
        internal static string Cryptography_MissingDomainParameters {
            get {
                return ResourceManager.GetString("Cryptography_MissingDomainParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cipher mode specified requires that an initialization vector (IV) be used..
        /// </summary>
        internal static string Cryptography_MissingIV {
            get {
                return ResourceManager.GetString("Cryptography_MissingIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the public key from the XML string..
        /// </summary>
        internal static string Cryptography_MissingPublicKey {
            get {
                return ResourceManager.GetString("Cryptography_MissingPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransformBlock may only process bytes in block sized increments..
        /// </summary>
        internal static string Cryptography_MustTransformWholeBlock {
            get {
                return ResourceManager.GetString("Cryptography_MustTransformWholeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms..
        /// </summary>
        internal static string Cryptography_NonCompliantFIPSAlgorithm {
            get {
                return ResourceManager.GetString("Cryptography_NonCompliantFIPSAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CNG key handle being opened was detected to be ephemeral, but the EphemeralKey open option was not specified..
        /// </summary>
        internal static string Cryptography_OpenEphemeralKeyHandleWithoutEphemeralFlag {
            get {
                return ResourceManager.GetString("Cryptography_OpenEphemeralKeyHandleWithoutEphemeralFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open an invalid handle..
        /// </summary>
        internal static string Cryptography_OpenInvalidHandle {
            get {
                return ResourceManager.GetString("Cryptography_OpenInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data is not a complete block..
        /// </summary>
        internal static string Cryptography_PartialBlock {
            get {
                return ResourceManager.GetString("Cryptography_PartialBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified cryptographic algorithm is not supported on this platform..
        /// </summary>
        internal static string Cryptography_PlatformNotSupported {
            get {
                return ResourceManager.GetString("Cryptography_PlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TLS key derivation function requires both the label and seed properties to be set..
        /// </summary>
        internal static string Cryptography_TlsRequiresLabelAndSeed {
            get {
                return ResourceManager.GetString("Cryptography_TlsRequiresLabelAndSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to transform beyond end of buffer..
        /// </summary>
        internal static string Cryptography_TransformBeyondEndOfBuffer {
            get {
                return ResourceManager.GetString("Cryptography_TransformBeyondEndOfBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML namespace &apos;{0}&apos; was unexpected, expected &apos;{1}&apos;..
        /// </summary>
        internal static string Cryptography_UnexpectedXmlNamespace {
            get {
                return ResourceManager.GetString("Cryptography_UnexpectedXmlNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown elliptic curve..
        /// </summary>
        internal static string Cryptography_UnknownEllipticCurve {
            get {
                return ResourceManager.GetString("Cryptography_UnknownEllipticCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown elliptic curve algorithm..
        /// </summary>
        internal static string Cryptography_UnknownEllipticCurveAlgorithm {
            get {
                return ResourceManager.GetString("Cryptography_UnknownEllipticCurveAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown padding mode used..
        /// </summary>
        internal static string Cryptography_UnknownPaddingMode {
            get {
                return ResourceManager.GetString("Cryptography_UnknownPaddingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default unless stated otherwise. In multithreaded applications, access streams in a thread-safe way, such as a thread-safe wrapper returned by TextReader&apos;s or TextWriter&apos;s Synchronized methods. This also applies to classes like StreamWriter and StreamReader..
        /// </summary>
        internal static string IndexOutOfRange_IORaceCondition {
            get {
                return ResourceManager.GetString("IndexOutOfRange_IORaceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRead can only be called once for each asynchronous operation..
        /// </summary>
        internal static string InvalidOperation_EndReadCalledMultiple {
            get {
                return ResourceManager.GetString("InvalidOperation_EndReadCalledMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndWaitForConnection can only be called once for each asynchronous operation..
        /// </summary>
        internal static string InvalidOperation_EndWaitForConnectionCalledMultiple {
            get {
                return ResourceManager.GetString("InvalidOperation_EndWaitForConnectionCalledMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndWrite can only be called once for each asynchronous operation..
        /// </summary>
        internal static string InvalidOperation_EndWriteCalledMultiple {
            get {
                return ResourceManager.GetString("InvalidOperation_EndWriteCalledMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was modified; enumeration operation may not execute..
        /// </summary>
        internal static string InvalidOperation_EnumFailedVersion {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumFailedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has either not started or has already finished..
        /// </summary>
        internal static string InvalidOperation_EnumOpCantHappen {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumOpCantHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in a connected state..
        /// </summary>
        internal static string InvalidOperation_PipeAlreadyConnected {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in a disconnected state..
        /// </summary>
        internal static string InvalidOperation_PipeAlreadyDisconnected {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeAlreadyDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe is closed..
        /// </summary>
        internal static string InvalidOperation_PipeClosed {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe is in a disconnected state..
        /// </summary>
        internal static string InvalidOperation_PipeDisconnected {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe handle has not been set.  Did your PipeStream implementation call InitializeHandle?.
        /// </summary>
        internal static string InvalidOperation_PipeHandleNotSet {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeHandleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pipe does not support message type transmission..
        /// </summary>
        internal static string InvalidOperation_PipeMessageTypeNotSupported {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeMessageTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe is not opened in asynchronous mode..
        /// </summary>
        internal static string InvalidOperation_PipeNotAsync {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeNotAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe hasn&apos;t been connected yet..
        /// </summary>
        internal static string InvalidOperation_PipeNotYetConnected {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeNotYetConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadMode is not of PipeTransmissionMode.Message..
        /// </summary>
        internal static string InvalidOperation_PipeReadModeNotMessage {
            get {
                return ResourceManager.GetString("InvalidOperation_PipeReadModeNotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time zone ID &apos;{0}&apos; was found on the local computer, but the registry information was corrupt..
        /// </summary>
        internal static string InvalidTimeZone_InvalidRegistryData {
            get {
                return ResourceManager.GetString("InvalidTimeZone_InvalidRegistryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Local time zone was found on the local computer, but the data was corrupt..
        /// </summary>
        internal static string InvalidTimeZone_InvalidWin32APIData {
            get {
                return ResourceManager.GetString("InvalidTimeZone_InvalidWin32APIData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the drive &apos;{0}&apos;. The drive might not be ready or might not be mapped..
        /// </summary>
        internal static string IO_DriveNotFound_Drive {
            get {
                return ResourceManager.GetString("IO_DriveNotFound_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read beyond the end of the stream..
        /// </summary>
        internal static string IO_EOF_ReadBeyondEOF {
            get {
                return ResourceManager.GetString("IO_EOF_ReadBeyondEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified file..
        /// </summary>
        internal static string IO_FileNotFound {
            get {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        internal static string IO_FileNotFound_FileName {
            get {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO operation will not work. Most likely the file will become too long or the handle was not opened to support synchronous IO operations..
        /// </summary>
        internal static string IO_FileTooLongOrHandleNotSync {
            get {
                return ResourceManager.GetString("IO_FileTooLongOrHandleNotSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create &quot;{0}&quot; because a file or directory with the same name already exists..
        /// </summary>
        internal static string IO_IO_AlreadyExists_Name {
            get {
                return ResourceManager.GetString("IO_IO_AlreadyExists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindHandle for ThreadPool failed on this handle..
        /// </summary>
        internal static string IO_IO_BindHandleFailed {
            get {
                return ResourceManager.GetString("IO_IO_BindHandleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists..
        /// </summary>
        internal static string IO_IO_FileExists_Name {
            get {
                return ResourceManager.GetString("IO_IO_FileExists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pipe handle..
        /// </summary>
        internal static string IO_IO_InvalidPipeHandle {
            get {
                return ResourceManager.GetString("IO_IO_InvalidPipeHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Path discovery permission to the specified directory was denied.&gt;.
        /// </summary>
        internal static string IO_IO_NoPermissionToDirectoryName {
            get {
                return ResourceManager.GetString("IO_IO_NoPermissionToDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe is broken..
        /// </summary>
        internal static string IO_IO_PipeBroken {
            get {
                return ResourceManager.GetString("IO_IO_PipeBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file &apos;{0}&apos; because it is being used by another process..
        /// </summary>
        internal static string IO_IO_SharingViolation_File {
            get {
                return ResourceManager.GetString("IO_IO_SharingViolation_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file because it is being used by another process..
        /// </summary>
        internal static string IO_IO_SharingViolation_NoFileName {
            get {
                return ResourceManager.GetString("IO_IO_SharingViolation_NoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path..
        /// </summary>
        internal static string IO_PathNotFound_NoPathName {
            get {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path &apos;{0}&apos;..
        /// </summary>
        internal static string IO_PathNotFound_Path {
            get {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..
        /// </summary>
        internal static string IO_PathTooLong {
            get {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A read lock may not be acquired with the write lock held in this mode..
        /// </summary>
        internal static string LockRecursionException_ReadAfterWriteNotAllowed {
            get {
                return ResourceManager.GetString("LockRecursionException_ReadAfterWriteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive read lock acquisitions not allowed in this mode..
        /// </summary>
        internal static string LockRecursionException_RecursiveReadNotAllowed {
            get {
                return ResourceManager.GetString("LockRecursionException_RecursiveReadNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive upgradeable lock acquisitions not allowed in this mode..
        /// </summary>
        internal static string LockRecursionException_RecursiveUpgradeNotAllowed {
            get {
                return ResourceManager.GetString("LockRecursionException_RecursiveUpgradeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive write lock acquisitions not allowed in this mode..
        /// </summary>
        internal static string LockRecursionException_RecursiveWriteNotAllowed {
            get {
                return ResourceManager.GetString("LockRecursionException_RecursiveWriteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgradeable lock may not be acquired with read lock held..
        /// </summary>
        internal static string LockRecursionException_UpgradeAfterReadNotAllowed {
            get {
                return ResourceManager.GetString("LockRecursionException_UpgradeAfterReadNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgradeable lock may not be acquired with write lock held in this mode. Acquiring Upgradeable lock gives the ability to read along with an option to upgrade to a writer..
        /// </summary>
        internal static string LockRecursionException_UpgradeAfterWriteNotAllowed {
            get {
                return ResourceManager.GetString("LockRecursionException_UpgradeAfterWriteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write lock may not be acquired with read lock held. This pattern is prone to deadlocks. Please ensure that read locks are released before taking a write lock. If an upgrade is necessary, use an upgrade lock in place of the read lock..
        /// </summary>
        internal static string LockRecursionException_WriteAfterReadNotAllowed {
            get {
                return ResourceManager.GetString("LockRecursionException_WriteAfterReadNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous pipes do not support PipeTransmissionMode.Message ReadMode..
        /// </summary>
        internal static string NotSupported_AnonymousPipeMessagesNotSupported {
            get {
                return ResourceManager.GetString("NotSupported_AnonymousPipeMessagesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous pipes can only be in one direction..
        /// </summary>
        internal static string NotSupported_AnonymousPipeUnidirectional {
            get {
                return ResourceManager.GetString("NotSupported_AnonymousPipeUnidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is only supported in Windows Vista and above..
        /// </summary>
        internal static string NotSupported_DownLevelVista {
            get {
                return ResourceManager.GetString("NotSupported_DownLevelVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Win32 devices other than file such as COM ports, printers, disk partitions and tape drives is not supported. Avoid use of &quot;\\.\&quot; in the path..
        /// </summary>
        internal static string NotSupported_IONonFileDevices {
            get {
                return ResourceManager.GetString("NotSupported_IONonFileDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory stream is not expandable..
        /// </summary>
        internal static string NotSupported_MemStreamNotExpandable {
            get {
                return ResourceManager.GetString("NotSupported_MemStreamNotExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting TextWriter is unsupported on this listener..
        /// </summary>
        internal static string NotSupported_SetTextWriter {
            get {
                return ResourceManager.GetString("NotSupported_SetTextWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string NotSupported_UnreadableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support seeking..
        /// </summary>
        internal static string NotSupported_UnseekableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnseekableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        internal static string NotSupported_UnwritableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed file..
        /// </summary>
        internal static string ObjectDisposed_FileClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_FileClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed pipe..
        /// </summary>
        internal static string ObjectDisposed_PipeClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_PipeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from a closed TextReader..
        /// </summary>
        internal static string ObjectDisposed_ReaderClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_ReaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed Stream..
        /// </summary>
        internal static string ObjectDisposed_StreamClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to a closed TextWriter..
        /// </summary>
        internal static string ObjectDisposed_WriterClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_WriterClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterId &apos;{0}&apos; already added to CounterSet &apos;{1}&apos;..
        /// </summary>
        internal static string Perflib_Argument_CounterAlreadyExists {
            get {
                return ResourceManager.GetString("Perflib_Argument_CounterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterName &apos;{0}&apos; already added to CounterSet &apos;{1}&apos;..
        /// </summary>
        internal static string Perflib_Argument_CounterNameAlreadyExists {
            get {
                return ResourceManager.GetString("Perflib_Argument_CounterNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterSet &apos;{0}&apos; already registered..
        /// </summary>
        internal static string Perflib_Argument_CounterSetAlreadyRegister {
            get {
                return ResourceManager.GetString("Perflib_Argument_CounterSetAlreadyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-empty counterName required..
        /// </summary>
        internal static string Perflib_Argument_EmptyCounterName {
            get {
                return ResourceManager.GetString("Perflib_Argument_EmptyCounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-empty instanceName required..
        /// </summary>
        internal static string Perflib_Argument_EmptyInstanceName {
            get {
                return ResourceManager.GetString("Perflib_Argument_EmptyInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance &apos;{0}&apos; already exists in CounterSet &apos;{1}&apos;..
        /// </summary>
        internal static string Perflib_Argument_InstanceAlreadyExists {
            get {
                return ResourceManager.GetString("Perflib_Argument_InstanceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterSetInstanceType &apos;{0}&apos; is not a valid CounterSetInstanceType..
        /// </summary>
        internal static string Perflib_Argument_InvalidCounterSetInstanceType {
            get {
                return ResourceManager.GetString("Perflib_Argument_InvalidCounterSetInstanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterType &apos;{0}&apos; is not a valid CounterType..
        /// </summary>
        internal static string Perflib_Argument_InvalidCounterType {
            get {
                return ResourceManager.GetString("Perflib_Argument_InvalidCounterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single instance type CounterSet &apos;{0}&apos; can only have 1 CounterSetInstance..
        /// </summary>
        internal static string Perflib_Argument_InvalidInstance {
            get {
                return ResourceManager.GetString("Perflib_Argument_InvalidInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterSet provider &apos;{0}&apos; not found..
        /// </summary>
        internal static string Perflib_Argument_ProviderNotFound {
            get {
                return ResourceManager.GetString("Perflib_Argument_ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot allocate memory for CounterSet &apos;{0}&apos; template with size &apos;{1}&apos;..
        /// </summary>
        internal static string Perflib_InsufficientMemory_CounterSetTemplate {
            get {
                return ResourceManager.GetString("Perflib_InsufficientMemory_CounterSetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot allocate raw counter data for CounterSet &apos;{0}&apos; Instance &apos;{1}&apos;..
        /// </summary>
        internal static string Perflib_InsufficientMemory_InstanceCounterBlock {
            get {
                return ResourceManager.GetString("Perflib_InsufficientMemory_InstanceCounterBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot AddCounter to CounterSet &apos;{0}&apos; after CreateCounterSetInstance..
        /// </summary>
        internal static string Perflib_InvalidOperation_AddCounterAfterInstance {
            get {
                return ResourceManager.GetString("Perflib_InvalidOperation_AddCounterAfterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate raw counter data location for CounterSet &apos;{0}&apos;, Counter &apos;{1}, in Instance &apos;{2}&apos;..
        /// </summary>
        internal static string Perflib_InvalidOperation_CounterRefValue {
            get {
                return ResourceManager.GetString("Perflib_InvalidOperation_CounterRefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterSet &apos;{0}&apos; does not include any counters..
        /// </summary>
        internal static string Perflib_InvalidOperation_CounterSetContainsNoCounter {
            get {
                return ResourceManager.GetString("Perflib_InvalidOperation_CounterSetContainsNoCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterSet &apos;{0}&apos; not installed yet..
        /// </summary>
        internal static string Perflib_InvalidOperation_CounterSetNotInstalled {
            get {
                return ResourceManager.GetString("Perflib_InvalidOperation_CounterSetNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Instance &apos;{0}&apos; in CounterSet &apos;{1}&apos;..
        /// </summary>
        internal static string Perflib_InvalidOperation_InstanceNotFound {
            get {
                return ResourceManager.GetString("Perflib_InvalidOperation_InstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterSet provider &apos;{0}&apos; not active..
        /// </summary>
        internal static string Perflib_InvalidOperation_NoActiveProvider {
            get {
                return ResourceManager.GetString("Perflib_InvalidOperation_NoActiveProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes in System.Diagnostics.PerformanceData is only supported in Windows Vista and above..
        /// </summary>
        internal static string Perflib_PlatformNotSupported {
            get {
                return ResourceManager.GetString("Perflib_PlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Pipe Servers are not supported on Windows 95/98/ME..
        /// </summary>
        internal static string PlatformNotSupported_NamedPipeServers {
            get {
                return ResourceManager.GetString("PlatformNotSupported_NamedPipeServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time zone ID &apos;{0}&apos; was found on the local computer, but the application does not have permission to read the registry information..
        /// </summary>
        internal static string Security_CannotReadRegistryData {
            get {
                return ResourceManager.GetString("Security_CannotReadRegistryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the field &apos;{0}&apos; is invalid.  The serialized data is corrupt.  .
        /// </summary>
        internal static string Serialization_CorruptField {
            get {
                return ResourceManager.GetString("Serialization_CorruptField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deserializing the object.  The serialized data is corrupt..
        /// </summary>
        internal static string Serialization_InvalidData {
            get {
                return ResourceManager.GetString("Serialization_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serialized data contained an invalid escape sequence &apos;\{0}&apos;..
        /// </summary>
        internal static string Serialization_InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("Serialization_InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keys for this dictionary are missing..
        /// </summary>
        internal static string Serialization_MissingKeys {
            get {
                return ResourceManager.GetString("Serialization_MissingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lock is being disposed while still being used. It either is being held by a thread and/or has active waiters waiting to acquire the lock..
        /// </summary>
        internal static string SynchronizationLockException_IncorrectDispose {
            get {
                return ResourceManager.GetString("SynchronizationLockException_IncorrectDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read lock is being released without being held..
        /// </summary>
        internal static string SynchronizationLockException_MisMatchedRead {
            get {
                return ResourceManager.GetString("SynchronizationLockException_MisMatchedRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upgradeable lock is being released without being held..
        /// </summary>
        internal static string SynchronizationLockException_MisMatchedUpgrade {
            get {
                return ResourceManager.GetString("SynchronizationLockException_MisMatchedUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The write lock is being released without being held..
        /// </summary>
        internal static string SynchronizationLockException_MisMatchedWrite {
            get {
                return ResourceManager.GetString("SynchronizationLockException_MisMatchedWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time zone ID &apos;{0}&apos; was not found on the local computer..
        /// </summary>
        internal static string TimeZoneNotFound_MissingRegistryData {
            get {
                return ResourceManager.GetString("TimeZoneNotFound_MissingRegistryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        internal static string TraceAsTraceSource {
            get {
                return ResourceManager.GetString("TraceAsTraceSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path is denied..
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_NoPathName {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path &apos;{0}&apos; is denied..
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_Path {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }
    }
}
