//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dynamic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dynamic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Properties.Dynamic", typeof(Dynamic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous conversion from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string AmbiguousConversion {
            get {
                return ResourceManager.GetString("AmbiguousConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary assignment failed due to null reference..
        /// </summary>
        internal static string BindBinaryAssignmentFailedNullReference {
            get {
                return ResourceManager.GetString("BindBinaryAssignmentFailedNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary assignment requires two arguments..
        /// </summary>
        internal static string BindBinaryAssignmentRequireTwoArguments {
            get {
                return ResourceManager.GetString("BindBinaryAssignmentRequireTwoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator requires two arguments..
        /// </summary>
        internal static string BindBinaryOperatorRequireTwoArguments {
            get {
                return ResourceManager.GetString("BindBinaryOperatorRequireTwoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind call failed - overload resolution failed..
        /// </summary>
        internal static string BindCallFailedOverloadResolution {
            get {
                return ResourceManager.GetString("BindCallFailedOverloadResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to conditional method &apos;{0}&apos; is not allowed..
        /// </summary>
        internal static string BindCallToConditionalMethod {
            get {
                return ResourceManager.GetString("BindCallToConditionalMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binder not compatible with call site.
        /// </summary>
        internal static string BinderNotCompatibleWithCallSite {
            get {
                return ResourceManager.GetString("BinderNotCompatibleWithCallSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit conversion requires one argument..
        /// </summary>
        internal static string BindExplicitConversionRequireOneArgument {
            get {
                return ResourceManager.GetString("BindExplicitConversionRequireOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit conversion requires one argument..
        /// </summary>
        internal static string BindImplicitConversionRequireOneArgument {
            get {
                return ResourceManager.GetString("BindImplicitConversionRequireOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding cannot be null.
        /// </summary>
        internal static string BindingCannotBeNull {
            get {
                return ResourceManager.GetString("BindingCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke failed: target is not a delegate..
        /// </summary>
        internal static string BindInvokeFailedNonDelegate {
            get {
                return ResourceManager.GetString("BindInvokeFailedNonDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bind property &apos;{0}&apos; to event &apos;{0}&apos;..
        /// </summary>
        internal static string BindPropertyFailedEvent {
            get {
                return ResourceManager.GetString("BindPropertyFailedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bind property &apos;{0}&apos; to method group..
        /// </summary>
        internal static string BindPropertyFailedMethodGroup {
            get {
                return ResourceManager.GetString("BindPropertyFailedMethodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding requires arguments..
        /// </summary>
        internal static string BindRequireArguments {
            get {
                return ResourceManager.GetString("BindRequireArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound to void method but a result was expected..
        /// </summary>
        internal static string BindToVoidMethodButExpectResult {
            get {
                return ResourceManager.GetString("BindToVoidMethodButExpectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operator requires one argument..
        /// </summary>
        internal static string BindUnaryOperatorRequireOneArgument {
            get {
                return ResourceManager.GetString("BindUnaryOperatorRequireOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call..
        /// </summary>
        internal static string CannotCall {
            get {
                return ResourceManager.GetString("CannotCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve type information..
        /// </summary>
        internal static string CannotRetrieveTypeInformation {
            get {
                return ResourceManager.GetString("CannotRetrieveTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM object does not support events..
        /// </summary>
        internal static string COMObjectDoesNotSupportEvents {
            get {
                return ResourceManager.GetString("COMObjectDoesNotSupportEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM object does not support source interface..
        /// </summary>
        internal static string COMObjectDoesNotSupportSourceInterface {
            get {
                return ResourceManager.GetString("COMObjectDoesNotSupportSourceInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM object expected..
        /// </summary>
        internal static string ComObjectExpected {
            get {
                return ResourceManager.GetString("ComObjectExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get DispId for &apos;{0}&apos; on &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotGetDispId {
            get {
                return ResourceManager.GetString("CouldNotGetDispId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameter count: {0}..
        /// </summary>
        internal static string DispBadParamCount {
            get {
                return ResourceManager.GetString("DispBadParamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; not found..
        /// </summary>
        internal static string DispMemberNotFound {
            get {
                return ResourceManager.GetString("DispMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named arguments are not supported: {0}..
        /// </summary>
        internal static string DispNoNamedArgs {
            get {
                return ResourceManager.GetString("DispNoNamedArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow: {0}..
        /// </summary>
        internal static string DispOverflow {
            get {
                return ResourceManager.GetString("DispOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not optional: {0}..
        /// </summary>
        internal static string DispParamNotOptional {
            get {
                return ResourceManager.GetString("DispParamNotOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch: {0} (expected {1})..
        /// </summary>
        internal static string DispTypeMismatch {
            get {
                return ResourceManager.GetString("DispTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic binder result not assignable.
        /// </summary>
        internal static string DynamicBinderResultNotAssignable {
            get {
                return ResourceManager.GetString("DynamicBinderResultNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic binding needs restrictions.
        /// </summary>
        internal static string DynamicBindingNeedsRestrictions {
            get {
                return ResourceManager.GetString("DynamicBindingNeedsRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic object result not assignable.
        /// </summary>
        internal static string DynamicObjectResultNotAssignable {
            get {
                return ResourceManager.GetString("DynamicObjectResultNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetIDsOfNames invalid: {0}..
        /// </summary>
        internal static string GetIDsOfNamesInvalid {
            get {
                return ResourceManager.GetString("GetIDsOfNamesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal compiler error..
        /// </summary>
        internal static string InternalCompilerError {
            get {
                return ResourceManager.GetString("InternalCompilerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument value..
        /// </summary>
        internal static string InvalidArgumentValue {
            get {
                return ResourceManager.GetString("InvalidArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should not be called..
        /// </summary>
        internal static string MethodShouldNotBeCalled {
            get {
                return ResourceManager.GetString("MethodShouldNotBeCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be reducible.
        /// </summary>
        internal static string MustBeReducible {
            get {
                return ResourceManager.GetString("MustBeReducible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must reduce to different.
        /// </summary>
        internal static string MustReduceToDifferent {
            get {
                return ResourceManager.GetString("MustReduceToDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null reference on member access..
        /// </summary>
        internal static string NullReferenceOnMemberException {
            get {
                return ResourceManager.GetString("NullReferenceOnMemberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced not compatible.
        /// </summary>
        internal static string ReducedNotCompatible {
            get {
                return ResourceManager.GetString("ReducedNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducible must override reduce.
        /// </summary>
        internal static string ReducibleMustOverrideReduce {
            get {
                return ResourceManager.GetString("ReducibleMustOverrideReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting COM object data failed..
        /// </summary>
        internal static string SetComObjectDataFailed {
            get {
                return ResourceManager.GetString("SetComObjectDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected VarEnum: {0}..
        /// </summary>
        internal static string UnexpectedVarEnum {
            get {
                return ResourceManager.GetString("UnexpectedVarEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported enum type..
        /// </summary>
        internal static string UnsupportedEnumType {
            get {
                return ResourceManager.GetString("UnsupportedEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported handler type..
        /// </summary>
        internal static string UnsupportedHandlerType {
            get {
                return ResourceManager.GetString("UnsupportedHandlerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant get accessor not implemented for &apos;{0}&apos;..
        /// </summary>
        internal static string VariantGetAccessorNYI {
            get {
                return ResourceManager.GetString("VariantGetAccessorNYI", resourceCulture);
            }
        }
    }
}
