//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Expressions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Expressions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Properties.Expressions", typeof(Expressions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument type cannot be System.Void..
        /// </summary>
        internal static string ArgumentCannotBeOfTypeVoid {
            get {
                return ResourceManager.GetString("ArgumentCannotBeOfTypeVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; is not declared on type &apos;{1}&apos; being created.
        /// </summary>
        internal static string ArgumentMemberNotDeclOnType {
            get {
                return ResourceManager.GetString("ArgumentMemberNotDeclOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be array.
        /// </summary>
        internal static string ArgumentMustBeArray {
            get {
                return ResourceManager.GetString("ArgumentMustBeArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument for array index must be of type Int32.
        /// </summary>
        internal static string ArgumentMustBeArrayIndexType {
            get {
                return ResourceManager.GetString("ArgumentMustBeArrayIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be boolean.
        /// </summary>
        internal static string ArgumentMustBeBoolean {
            get {
                return ResourceManager.GetString("ArgumentMustBeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument for a checked operation must be of type Int32, UInt32, Int64 or UInt64.
        /// </summary>
        internal static string ArgumentMustBeCheckable {
            get {
                return ResourceManager.GetString("ArgumentMustBeCheckable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument type must be comparable.
        /// </summary>
        internal static string ArgumentMustBeComparable {
            get {
                return ResourceManager.GetString("ArgumentMustBeComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of a convertible type.
        /// </summary>
        internal static string ArgumentMustBeConvertible {
            get {
                return ResourceManager.GetString("ArgumentMustBeConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be either a FieldInfo or PropertyInfo.
        /// </summary>
        internal static string ArgumentMustBeFieldInfoOrPropertInfo {
            get {
                return ResourceManager.GetString("ArgumentMustBeFieldInfoOrPropertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be either a FieldInfo, PropertyInfo or MethodInfo.
        /// </summary>
        internal static string ArgumentMustBeFieldInfoOrPropertInfoOrMethod {
            get {
                return ResourceManager.GetString("ArgumentMustBeFieldInfoOrPropertInfoOrMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be an instance member.
        /// </summary>
        internal static string ArgumentMustBeInstanceMember {
            get {
                return ResourceManager.GetString("ArgumentMustBeInstanceMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type Int32.
        /// </summary>
        internal static string ArgumentMustBeInt32 {
            get {
                return ResourceManager.GetString("ArgumentMustBeInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of an integer type.
        /// </summary>
        internal static string ArgumentMustBeInteger {
            get {
                return ResourceManager.GetString("ArgumentMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of an integer or boolean type.
        /// </summary>
        internal static string ArgumentMustBeIntegerOrBoolean {
            get {
                return ResourceManager.GetString("ArgumentMustBeIntegerOrBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of a numeric type.
        /// </summary>
        internal static string ArgumentMustBeNumeric {
            get {
                return ResourceManager.GetString("ArgumentMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be single dimensional array type.
        /// </summary>
        internal static string ArgumentMustBeSingleDimensionalArrayType {
            get {
                return ResourceManager.GetString("ArgumentMustBeSingleDimensionalArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument type &apos;{0}&apos; does not match the corresponding member type &apos;{1}&apos;.
        /// </summary>
        internal static string ArgumentTypeDoesNotMatchMember {
            get {
                return ResourceManager.GetString("ArgumentTypeDoesNotMatchMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument types do not match.
        /// </summary>
        internal static string ArgumentTypesMustMatch {
            get {
                return ResourceManager.GetString("ArgumentTypesMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binary operator {0} is not defined for the types &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string BinaryOperatorNotDefined {
            get {
                return ResourceManager.GetString("BinaryOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot auto initialize elements of value type through property &apos;{0}&apos;, use assignment instead.
        /// </summary>
        internal static string CannotAutoInitializeValueTypeElementThroughProperty {
            get {
                return ResourceManager.GetString("CannotAutoInitializeValueTypeElementThroughProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot auto initialize members of value type through property &apos;{0}&apos;, use assignment instead.
        /// </summary>
        internal static string CannotAutoInitializeValueTypeMemberThroughProperty {
            get {
                return ResourceManager.GetString("CannotAutoInitializeValueTypeMemberThroughProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression of type &apos;{0}&apos; cannot be cast to type &apos;{1}&apos;.
        /// </summary>
        internal static string CannotCastTypeToType {
            get {
                return ResourceManager.GetString("CannotCastTypeToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coalesce used with type that cannot be null.
        /// </summary>
        internal static string CoalesceUsedOnNonNullType {
            get {
                return ResourceManager.GetString("CoalesceUsedOnNonNullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coercion operator is defined between types &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string CoercionOperatorNotDefined {
            get {
                return ResourceManager.GetString("CoercionOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; of element initializer method &apos;{1}&apos; must not be a pass by reference parameter.
        /// </summary>
        internal static string ElementInitializerMethodNoRefOutParam {
            get {
                return ResourceManager.GetString("ElementInitializerMethodNoRefOutParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element initializer method must be named &apos;Add&apos;.
        /// </summary>
        internal static string ElementInitializerMethodNotAdd {
            get {
                return ResourceManager.GetString("ElementInitializerMethodNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element initializer method must be an instance method.
        /// </summary>
        internal static string ElementInitializerMethodStatic {
            get {
                return ResourceManager.GetString("ElementInitializerMethodStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element initializer method must have at least 1 parameter.
        /// </summary>
        internal static string ElementInitializerMethodWithZeroArgs {
            get {
                return ResourceManager.GetString("ElementInitializerMethodWithZeroArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lambda expression cannot contain pass by reference parameters..
        /// </summary>
        internal static string ExpressionMayNotContainByrefParameters {
            get {
                return ResourceManager.GetString("ExpressionMayNotContainByrefParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression of type &apos;{0}&apos; cannot be used to initialize an array of type &apos;{1}&apos;.
        /// </summary>
        internal static string ExpressionTypeCannotInitializeArrayType {
            get {
                return ResourceManager.GetString("ExpressionTypeCannotInitializeArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression of type &apos;{0}&apos; cannot be used to initialize an collection of type &apos;{1}&apos;.
        /// </summary>
        internal static string ExpressionTypeCannotInitializeCollectionType {
            get {
                return ResourceManager.GetString("ExpressionTypeCannotInitializeCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression of type &apos;{0}&apos; cannot be used to initialize an array of type &apos;{1}&apos;.
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchArrayType {
            get {
                return ResourceManager.GetString("ExpressionTypeDoesNotMatchArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of type &apos;{0}&apos; cannot be used for constructor parameter of type &apos;{1}&apos;.
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchConstructorParameter {
            get {
                return ResourceManager.GetString("ExpressionTypeDoesNotMatchConstructorParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of type &apos;{0}&apos; cannot be used for parameter of type &apos;{1}&apos; of method &apos;{2}&apos;.
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchMethodParameter {
            get {
                return ResourceManager.GetString("ExpressionTypeDoesNotMatchMethodParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of type &apos;{0}&apos; cannot be used for parameter of type &apos;{1}&apos;.
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchParameter {
            get {
                return ResourceManager.GetString("ExpressionTypeDoesNotMatchParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of type &apos;{0}&apos; cannot be used for return type &apos;{1}&apos;.
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchReturn {
            get {
                return ResourceManager.GetString("ExpressionTypeDoesNotMatchReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of type &apos;{0}&apos; cannot be invoked.
        /// </summary>
        internal static string ExpressionTypeNotInvocable {
            get {
                return ResourceManager.GetString("ExpressionTypeNotInvocable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not defined for type &apos;{1}&apos;.
        /// </summary>
        internal static string FieldNotDefinedForType {
            get {
                return ResourceManager.GetString("FieldNotDefinedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments for the given members .
        /// </summary>
        internal static string IncorrectNumberOfArgumentsForMembers {
            get {
                return ResourceManager.GetString("IncorrectNumberOfArgumentsForMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments for constructor.
        /// </summary>
        internal static string IncorrectNumberOfConstructorArguments {
            get {
                return ResourceManager.GetString("IncorrectNumberOfConstructorArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of indexes.
        /// </summary>
        internal static string IncorrectNumberOfIndexes {
            get {
                return ResourceManager.GetString("IncorrectNumberOfIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments supplied for lambda invocation.
        /// </summary>
        internal static string IncorrectNumberOfLambdaArguments {
            get {
                return ResourceManager.GetString("IncorrectNumberOfLambdaArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of parameters supplied for lambda declaration.
        /// </summary>
        internal static string IncorrectNumberOfLambdaDeclarationParameters {
            get {
                return ResourceManager.GetString("IncorrectNumberOfLambdaDeclarationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of members for constructor.
        /// </summary>
        internal static string IncorrectNumberOfMembersForGivenConstructor {
            get {
                return ResourceManager.GetString("IncorrectNumberOfMembersForGivenConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments supplied for call to method &apos;{0}&apos;.
        /// </summary>
        internal static string IncorrectNumberOfMethodCallArguments {
            get {
                return ResourceManager.GetString("IncorrectNumberOfMethodCallArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect number of type args were specified for the declaration of an Action type..
        /// </summary>
        internal static string IncorrectNumberOfTypeArgsForAction {
            get {
                return ResourceManager.GetString("IncorrectNumberOfTypeArgsForAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect number of type args were specified for the declaration of a Func type..
        /// </summary>
        internal static string IncorrectNumberOfTypeArgsForFunc {
            get {
                return ResourceManager.GetString("IncorrectNumberOfTypeArgsForFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type used in TypeAs Expression must be of reference or nullable type, {0} is neither.
        /// </summary>
        internal static string IncorrectTypeForTypeAs {
            get {
                return ResourceManager.GetString("IncorrectTypeForTypeAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast from type &apos;{0}&apos; to type &apos;{1}.
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda Parameter not in scope.
        /// </summary>
        internal static string LambdaParameterNotInScope {
            get {
                return ResourceManager.GetString("LambdaParameterNotInScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda type parameter must be derived from System.Delegate.
        /// </summary>
        internal static string LambdaTypeMustBeDerivedFromSystemDelegate {
            get {
                return ResourceManager.GetString("LambdaTypeMustBeDerivedFromSystemDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List initializers must contain at least one initializer.
        /// </summary>
        internal static string ListInitializerWithZeroMembers {
            get {
                return ResourceManager.GetString("ListInitializerWithZeroMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user-defined operator method &apos;{1}&apos; for operator &apos;{0}&apos; must have associated boolean True and False operators..
        /// </summary>
        internal static string LogicalOperatorMustHaveBooleanOperators {
            get {
                return ResourceManager.GetString("LogicalOperatorMustHaveBooleanOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user-defined operator method &apos;{1}&apos; for operator &apos;{0}&apos; must have identical parameter and return types..
        /// </summary>
        internal static string LogicalOperatorMustHaveConsistentTypes {
            get {
                return ResourceManager.GetString("LogicalOperatorMustHaveConsistentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; not field or property.
        /// </summary>
        internal static string MemberNotFieldOrProperty {
            get {
                return ResourceManager.GetString("MemberNotFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} contains generic parameters.
        /// </summary>
        internal static string MethodContainsGenericParameters {
            get {
                return ResourceManager.GetString("MethodContainsGenericParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method &apos;{0}&apos; exists on type &apos;{1}&apos;..
        /// </summary>
        internal static string MethodDoesNotExistOnType {
            get {
                return ResourceManager.GetString("MethodDoesNotExistOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} is a generic method definition.
        /// </summary>
        internal static string MethodIsGeneric {
            get {
                return ResourceManager.GetString("MethodIsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is not defined for type &apos;{1}&apos;.
        /// </summary>
        internal static string MethodNotDefinedForType {
            get {
                return ResourceManager.GetString("MethodNotDefinedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}.{1}&apos; is not a property accessor.
        /// </summary>
        internal static string MethodNotPropertyAccessor {
            get {
                return ResourceManager.GetString("MethodNotPropertyAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method &apos;{0}&apos; on type &apos;{1}&apos; is compatible with the supplied arguments..
        /// </summary>
        internal static string MethodWithArgsDoesNotExistOnType {
            get {
                return ResourceManager.GetString("MethodWithArgsDoesNotExistOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one method &apos;{0}&apos; on type &apos;{1}&apos; is compatible with the supplied arguments..
        /// </summary>
        internal static string MethodWithMoreThanOneMatch {
            get {
                return ResourceManager.GetString("MethodWithMoreThanOneMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a member of type &apos;{1}&apos;.
        /// </summary>
        internal static string NotAMemberOfType {
            get {
                return ResourceManager.GetString("NotAMemberOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operands for operator &apos;{0}&apos; do not match the parameters of method &apos;{1}&apos;..
        /// </summary>
        internal static string OperandTypesDoNotMatchParameters {
            get {
                return ResourceManager.GetString("OperandTypesDoNotMatchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; is not implemented for type &apos;{1}&apos;.
        /// </summary>
        internal static string OperatorNotImplementedForType {
            get {
                return ResourceManager.GetString("OperatorNotImplementedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLinq.
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterExpression of type &apos;{0}&apos; cannot be used for delegate parameter of type &apos;{1}&apos;.
        /// </summary>
        internal static string ParameterExpressionNotValidAsDelegate {
            get {
                return ResourceManager.GetString("ParameterExpressionNotValidAsDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not captured.
        /// </summary>
        internal static string ParameterNotCaptured {
            get {
                return ResourceManager.GetString("ParameterNotCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; has no &apos;get&apos; accessor.
        /// </summary>
        internal static string PropertyDoesNotHaveGetter {
            get {
                return ResourceManager.GetString("PropertyDoesNotHaveGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; has no &apos;set&apos; accessor.
        /// </summary>
        internal static string PropertyDoesNotHaveSetter {
            get {
                return ResourceManager.GetString("PropertyDoesNotHaveSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not defined for type &apos;{1}&apos;.
        /// </summary>
        internal static string PropertyNotDefinedForType {
            get {
                return ResourceManager.GetString("PropertyNotDefinedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} contains generic parameters.
        /// </summary>
        internal static string TypeContainsGenericParameters {
            get {
                return ResourceManager.GetString("TypeContainsGenericParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is a generic type definition.
        /// </summary>
        internal static string TypeIsGeneric {
            get {
                return ResourceManager.GetString("TypeIsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a default constructor.
        /// </summary>
        internal static string TypeMissingDefaultConstructor {
            get {
                return ResourceManager.GetString("TypeMissingDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not IEnumerable.
        /// </summary>
        internal static string TypeNotIEnumerable {
            get {
                return ResourceManager.GetString("TypeNotIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameter is {0}. Expected a delegate..
        /// </summary>
        internal static string TypeParameterIsNotDelegate {
            get {
                return ResourceManager.GetString("TypeParameterIsNotDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unary operator {0} is not defined for the type &apos;{1}&apos;..
        /// </summary>
        internal static string UnaryOperatorNotDefined {
            get {
                return ResourceManager.GetString("UnaryOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected coalesce operator..
        /// </summary>
        internal static string UnexpectedCoalesceOperator {
            get {
                return ResourceManager.GetString("UnexpectedCoalesceOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled binary: {0}.
        /// </summary>
        internal static string UnhandledBinary {
            get {
                return ResourceManager.GetString("UnhandledBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled binding .
        /// </summary>
        internal static string UnhandledBinding {
            get {
                return ResourceManager.GetString("UnhandledBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Binding Type: {0}.
        /// </summary>
        internal static string UnhandledBindingType {
            get {
                return ResourceManager.GetString("UnhandledBindingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled method call: {0}.
        /// </summary>
        internal static string UnhandledCall {
            get {
                return ResourceManager.GetString("UnhandledCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled convert: {0}.
        /// </summary>
        internal static string UnhandledConvert {
            get {
                return ResourceManager.GetString("UnhandledConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled convert from decimal to {0}.
        /// </summary>
        internal static string UnhandledConvertFromDecimal {
            get {
                return ResourceManager.GetString("UnhandledConvertFromDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled convert to decimal from {0}.
        /// </summary>
        internal static string UnhandledConvertToDecimal {
            get {
                return ResourceManager.GetString("UnhandledConvertToDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Expression Type: {0}.
        /// </summary>
        internal static string UnhandledExpressionType {
            get {
                return ResourceManager.GetString("UnhandledExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled member access: {0}.
        /// </summary>
        internal static string UnhandledMemberAccess {
            get {
                return ResourceManager.GetString("UnhandledMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled unary: {0}.
        /// </summary>
        internal static string UnhandledUnary {
            get {
                return ResourceManager.GetString("UnhandledUnary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown binding type.
        /// </summary>
        internal static string UnknownBindingType {
            get {
                return ResourceManager.GetString("UnknownBindingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined operator method &apos;{0}&apos; must be static..
        /// </summary>
        internal static string UserDefinedOperatorMustBeStatic {
            get {
                return ResourceManager.GetString("UserDefinedOperatorMustBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined operator method &apos;{0}&apos; must not be void..
        /// </summary>
        internal static string UserDefinedOperatorMustNotBeVoid {
            get {
                return ResourceManager.GetString("UserDefinedOperatorMustNotBeVoid", resourceCulture);
            }
        }
    }
}
